# Generated by Django 3.2.13 on 2023-09-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('impacto', models.CharField(choices=[('A', 'Muito Marcante'), ('M', 'Marcante'), ('N', 'Nem tão marcante')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Estatisticas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('numeros', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informacoes', models.CharField(max_length=15)),
            ],
        ),
    ]
